/* Auto-generated from nuvio-osc.lua */
#ifndef NUVIO_OSC_LUA_H
#define NUVIO_OSC_LUA_H

static const char NUVIO_OSC_LUA[] =
    "-- Nuvio custom OSC for mpv — renders inside the video surface\n"
    "-- Works on both X11 and Wayland (no transparency issues)\n"
    "local mp = require 'mp'\n"
    "local utils = require 'mp.utils'\n"
    "local assdraw = require 'mp.assdraw'\n"
    "\n"
    "-- Config\n"
    "local VIS_TIMEOUT = 3\n"
    "local BAR_H = 4\n"
    "local BOTTOM_PAD = 55\n"
    "local TOP_PAD = 35\n"
    "\n"
    "-- State\n"
    "local State = {\n"
    "    pos = 0,\n"
    "    dur = 0,\n"
    "    paused = false,\n"
    "    loading = false,\n"
    "    visible = true,\n"
    "    hover_progress = nil, -- nil = not hovering seekbar\n"
    "    title = '',\n"
    "    mouse_y = -1,\n"
    "    w = 1920,\n"
    "    h = 1080,\n"
    "}\n"
    "\n"
    "local overlay = nil\n"
    "local hide_timer = nil\n"
    "\n"
    "local function fmt_time(s)\n"
    "    if not s or s < 0 then return '0:00' end\n"
    "    s = math.floor(s)\n"
    "    return string.format('%d:%02d', math.floor(s / 60), s % 60)\n"
    "end\n"
    "\n"
    "local function update_size()\n"
    "    local w = mp.get_property_number('osd-width', 0)\n"
    "    local h = mp.get_property_number('osd-height', 0)\n"
    "    if w > 0 and h > 0 then\n"
    "        State.w = w\n"
    "        State.h = h\n"
    "    end\n"
    "end\n"
    "\n"
    "mp.msg.info(\"nuvio-osc: script loaded, version 5\")\n"
    "\n"
    "local function draw()\n"
    "    update_size()\n"
    "    local w, h = State.w, State.h\n"
    "    mp.msg.verbose(\"nuvio-osc: draw w=\" .. w .. \" h=\" .. h .. \" visible=\" .. tostring(State.visible))\n"
    "\n"
    "    local progress = 0\n"
    "    if State.dur > 0 then\n"
    "        progress = State.pos / State.dur\n"
    "    end\n"
    "    if progress < 0 then progress = 0 end\n"
    "    if progress > 1 then progress = 1 end\n"
    "\n"
    "    local bar_x = 25\n"
    "    local bar_w = w - 50\n"
    "    local bar_y = h - BOTTOM_PAD\n"
    "\n"
    "    local s = assdraw.ass_new()\n"
    "\n"
    "    -- Fullscreen background scrim when visible\n"
    "    if State.visible then\n"
    "        -- Top scrim gradient (4 layers)\n"
    "        for i = 0, 3 do\n"
    "            local a = math.floor(180 - i * 45)\n"
    "            local ah = string.format('%X', a):sub(-2)\n"
    "            s:append('{\\\\pos(0,0)\\\\bord0\\\\shad0\\\\1c&H000000&\\\\1a&H' .. ah .. '&}')\n"
    "            s:append('{\\\\p1}m 0 0 l ' .. w .. ' 0 ' .. w .. ' ' .. (50 + i * 25) .. ' 0 ' .. (50 + i * 25) .. '{\\\\p0}')\n"
    "        end\n"
    "        -- Bottom scrim gradient (6 layers)\n"
    "        for i = 0, 5 do\n"
    "            local a = math.floor(30 + i * 35)\n"
    "            local ah = string.format('%X', a):sub(-2)\n"
    "            local y0 = h - BOTTOM_PAD - 80 + i * 15\n"
    "            s:append('{\\\\pos(0,' .. y0 .. ')\\\\bord0\\\\shad0\\\\1c&H000000&\\\\1a&H' .. ah .. '&}')\n"
    "            s:append('{\\\\p1}m 0 0 l ' .. w .. ' 0 ' .. w .. ' 20 0 20{\\\\p0}')\n"
    "        end\n"
    "    end\n"
    "\n"
    "    if State.visible then\n"
    "        -- Title (top-left)\n"
    "        if State.title ~= '' then\n"
    "            s:new_event()\n"
    "            s:append('{\\\\pos(25,' .. TOP_PAD .. ')\\\\bord1\\\\shad1\\\\1c&HFFFFFF&\\\\3c&H000000&\\\\fs18\\\\fnSansSerif\\\\b1}')\n"
    "            s:append(State.title)\n"
    "        end\n"
    "\n"
    "        -- Seekbar background\n"
    "        s:new_event()\n"
    "        s:append('{\\\\pos(' .. bar_x .. ',' .. bar_y .. ')\\\\bord0\\\\shad0\\\\1c&H333333&\\\\1a&H40&}')\n"
    "        s:append('{\\\\p1}m 0 0 l ' .. bar_w .. ' 0 ' .. bar_w .. ' ' .. BAR_H .. ' 0 ' .. BAR_H .. '{\\\\p0}')\n"
    "\n"
    "        -- Seekbar progress\n"
    "        if progress > 0 then\n"
    "            local pw = math.floor(bar_w * progress)\n"
    "            s:new_event()\n"
    "            s:append('{\\\\pos(' .. bar_x .. ',' .. bar_y .. ')\\\\bord0\\\\shad0\\\\1c&H2F6FED&\\\\1a&H00&}')\n"
    "            s:append('{\\\\p1}m 0 0 l ' .. pw .. ' 0 ' .. pw .. ' ' .. BAR_H .. ' 0 ' .. BAR_H .. '{\\\\p0}')\n"
    "        end\n"
    "\n"
    "        -- Seekbar handle (circle)\n"
    "        local hx = bar_x + math.floor(bar_w * progress)\n"
    "        local hr = 8\n"
    "        s:new_event()\n"
    "        s:append('{\\\\pos(' .. (hx - hr) .. ',' .. (bar_y - hr + BAR_H / 2) .. ')\\\\bord0\\\\shad0\\\\1c&HFFFFFF&\\\\1a&H00&}')\n"
    "        s:append('{\\\\p1}m ' .. hr .. ' 0 b ' .. hr .. ' -' .. hr .. ' 0 -' .. hr .. ' -' .. hr .. ' -' .. hr .. ' -' .. hr .. ' 0 -' .. hr .. ' ' .. hr .. ' 0 ' .. hr .. ' ' .. hr .. ' 0 ' .. hr .. ' ' .. hr .. ' ' .. hr .. ' b ' .. hr .. ' ' .. hr .. ' 0 ' .. hr .. ' -' .. hr .. ' ' .. hr .. ' -' .. hr .. ' ' .. hr .. '{\\\\p0}')\n"
    "\n"
    "        -- Time labels\n"
    "        local time_str = fmt_time(State.pos) .. ' / ' .. fmt_time(State.dur)\n"
    "        s:new_event()\n"
    "        s:append('{\\\\pos(' .. bar_x .. ',' .. (bar_y + BAR_H + 18) .. ')\\\\bord1\\\\shad1\\\\1c&HFFFFFF&\\\\3c&H000000&\\\\fs14\\\\fnSansSerif}')\n"
    "        s:append(time_str)\n"
    "\n"
    "        -- Play/Pause icon (center)\n"
    "        local icon_y = math.floor(h / 2 - 20)\n"
    "        if State.paused then\n"
    "            -- Play triangle\n"
    "            s:new_event()\n"
    "            local cx = math.floor(w / 2)\n"
    "            local sz = 25\n"
    "            s:append('{\\\\pos(' .. (cx - sz / 3) .. ',' .. (icon_y - sz) .. ')\\\\bord2\\\\shad1\\\\1c&HFFFFFF&\\\\3c&H000000&\\\\fs1\\\\fnSansSerif}')\n"
    "            s:append('{\\\\p1}m 0 0 l ' .. sz .. ' ' .. sz .. ' l 0 ' .. (sz * 2) .. '{\\\\p0}')\n"
    "        else\n"
    "            -- Pause bars\n"
    "            s:new_event()\n"
    "            local cx = math.floor(w / 2)\n"
    "            local bw = 8\n"
    "            local gap = 12\n"
    "            local bh = 40\n"
    "            s:append('{\\\\pos(' .. (cx - gap - bw) .. ',' .. icon_y .. ')\\\\bord0\\\\shad0\\\\1c&HFFFFFF&\\\\1a&H00&}')\n"
    "            s:append('{\\\\p1}m 0 0 l ' .. bw .. ' 0 ' .. bw .. ' ' .. bh .. ' 0 ' .. bh .. '{\\\\p0}')\n"
    "            s:new_event()\n"
    "            s:append('{\\\\pos(' .. (cx + gap) .. ',' .. icon_y .. ')\\\\bord0\\\\shad0\\\\1c&HFFFFFF&\\\\1a&H00&}')\n"
    "            s:append('{\\\\p1}m 0 0 l ' .. bw .. ' 0 ' .. bw .. ' ' .. bh .. ' 0 ' .. bh .. '{\\\\p0}')\n"
    "        end\n"
    "\n"
    "        -- Loading spinner\n"
    "        if State.loading then\n"
    "            local angle = math.floor((mp.get_time() * 5) % 360)\n"
    "            local cx, cy = math.floor(w / 2), math.floor(h / 2 + 50)\n"
    "            local r = 18\n"
    "            s:new_event()\n"
    "            s:append('{\\\\pos(' .. (cx - r) .. ',' .. (cy - r) .. ')\\\\bord3\\\\shad0\\\\1c&HAAAAAA&\\\\3c&H000000&\\\\1a&H00&}')\n"
    "            s:append('{\\\\p1}m ' .. r .. ' 0 b ' .. r .. ' ' .. r .. ' 0 ' .. r .. ' -' .. r .. ' ' .. r .. ' -' .. r .. ' 0 -' .. r .. ' -' .. r .. ' 0 -' .. r .. ' -' .. r .. '{\\\\p0}')\n"
    "        end\n"
    "    end\n"
    "\n"
    "    if not overlay then\n"
    "        overlay = mp.create_osd_overlay('ass-events')\n"
    "    end\n"
    "    overlay.data = s.text\n"
    "    overlay:update()\n"
    "end\n"
    "\n"
    "local function show()\n"
    "    State.visible = true\n"
    "    draw()\n"
    "    if hide_timer then hide_timer:kill() end\n"
    "    hide_timer = mp.add_timeout(VIS_TIMEOUT, function()\n"
    "        State.visible = false\n"
    "        draw()\n"
    "    end)\n"
    "end\n"
    "\n"
    "-- Property observers\n"
    "mp.observe_property('time-pos', 'number', function(_, val)\n"
    "    State.pos = val or 0\n"
    "    draw()\n"
    "end)\n"
    "mp.observe_property('duration', 'number', function(_, val)\n"
    "    State.dur = val or 0\n"
    "    draw()\n"
    "end)\n"
    "mp.observe_property('pause', 'bool', function(_, val)\n"
    "    State.paused = val or false\n"
    "    draw()\n"
    "end)\n"
    "mp.observe_property('idle-active', 'bool', function(_, val)\n"
    "    State.loading = val or false\n"
    "    draw()\n"
    "end)\n"
    "mp.observe_property('media-title', 'string', function(_, val)\n"
    "    State.title = val or ''\n"
    "    draw()\n"
    "end)\n"
    "\n"
    "-- Mouse events\n"
    "mp.register_event('mouse-move', function()\n"
    "    show()\n"
    "end)\n"
    "\n"
    "mp.register_script_message('mouse-click', function(btn)\n"
    "    if btn == 'left' then\n"
    "        mp.command('cycle pause')\n"
    "        show()\n"
    "    elseif btn == 'right' then\n"
    "        mp.command('cycle fullscreen')\n"
    "    end\n"
    "end)\n"
    "\n"
    "-- Bind mouse clicks via input-conf is not possible from Lua,\n"
    "-- so we use a different approach: register key bindings\n"
    "mp.add_key_binding('MBTN_LEFT', 'osc-click', function()\n"
    "    mp.command('cycle pause')\n"
    "    show()\n"
    "end)\n"
    "\n"
    "mp.add_key_binding('MBTN_LEFT_DBL', 'osc-dblclick', function()\n"
    "    mp.command('cycle fullscreen')\n"
    "    show()\n"
    "end)\n"
    "\n"
    "mp.add_key_binding('WHEEL_UP', 'osc-wheel-up', function()\n"
    "    mp.command('seek 5')\n"
    "    show()\n"
    "end)\n"
    "\n"
    "mp.add_key_binding('WHEEL_DOWN', 'osc-wheel-down', function()\n"
    "    mp.command('seek -5')\n"
    "    show()\n"
    "end)\n"
    "\n"
    "-- Initial show\n"
    "show()\n"
    "\n"
;

#endif
